/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as fromLessons from "../fromLessons.js";
import type * as fromProgress from "../fromProgress.js";
import type * as fromStaticContent from "../fromStaticContent.js";
import type * as fromStripe from "../fromStripe.js";
import type * as fromUsers from "../fromUsers.js";
import type * as http from "../http.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  fromLessons: typeof fromLessons;
  fromProgress: typeof fromProgress;
  fromStaticContent: typeof fromStaticContent;
  fromStripe: typeof fromStripe;
  fromUsers: typeof fromUsers;
  http: typeof http;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
